# Server Configuration
server:
  port: 8080
  gin_mode: release

# PGSQL Database Configuration
database:
  host: localhost
  port: 5432
  name: mydatabase
  user: dbuser
  password: securepassword
  schema: public

# Log Configuration
log:
  level: info
  outputs: stdout,file
  app_log_path: ./logs/app.log
  error_log_path: ./logs/error.log